name: ${COMPOSE_PROJECT_NAME}

services:
  php:
    build:
      context: ./docker/php
    container_name: php
    volumes:
      - ./app:/var/www/app
    networks:
      - project-network
    user: 1000:1000

  nginx:
    build:
      context: ./docker/nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/app
      - nginx-logs:/var/log/nginx
    depends_on:
      - php
    networks:
      - project-network

  db:
    image: postgres:17.0-alpine3.20
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-logs:/var/log/postgresql
    networks:
      - project-network

volumes:
  db-data:
  db-logs:
  nginx-logs:

networks:
  project-network:
    driver: bridge